{"name": "test_login", "status": "broken", "statusDetails": {"message": "TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'", "trace": "@pytest.fixture\n    def driver():\n>       driver = webdriver.Chrome(executable_path=r\"C:\\Users\\Soumick\\Desktop\\cv\\Selenium\\chromedriver_win32\\chromedriver.exe\")\nE       TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'\n\nallure_report.py:12: TypeError"}, "start": 1686204002954, "stop": 1686204002954, "uuid": "c439b6b7-0080-49db-b422-68f7197e989b", "historyId": "6b96cdebe3b18d1f451a4b81b33314e4", "testCaseId": "6b96cdebe3b18d1f451a4b81b33314e4", "fullName": "allure_report#test_login", "labels": [{"name": "suite", "value": "allure_report"}, {"name": "host", "value": "DESKTOP-93NIJVK"}, {"name": "thread", "value": "68780-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "allure_report"}]}