{"uuid": "52a4d840-95e0-4b99-87a4-99fe5833efae", "children": ["c439b6b7-0080-49db-b422-68f7197e989b"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'\n", "trace": "  File \"C:\\Users\\Soumick\\Desktop\\cv\\Selenium\\automation\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Soumick\\Desktop\\cv\\Selenium\\automation\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Soumick\\Desktop\\cv\\Selenium\\automation\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Soumick\\Desktop\\cv\\Selenium\\allure_report.py\", line 12, in driver\n    driver = webdriver.Chrome(executable_path=r\"C:\\Users\\Soumick\\Desktop\\cv\\Selenium\\chromedriver_win32\\chromedriver.exe\")\n"}, "start": 1686204002956, "stop": 1686204002957}], "start": 1686204002956, "stop": 1686204003099}