[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B67E4BF40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c5ec168b7b92c475c096b705fd0fef7f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B67E4BE80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c5ec168b7b92c475c096b705fd0fef7f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B67E4B7C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c5ec168b7b92c475c096b705fd0fef7f